### ISSUE TITLE
个人的提问列表

### ISSUE THREAD

**Issue by hcjcch** [ifLab/WeCenterMobile-Api#13]
![image](https://cloud.githubusercontent.com/assets/4105329/9287439/7c9e0956-4347-11e5-87bd-4d004ab58c41.png)
http://we.bistu.edu.cn/api/my_question.php?uid=4&page=100
这个链接里面的数组不会返回[]，而返回的总是最后一页数据，@Msr-B 你里面有这个bug

**Comment by hihwei** [comment]
该接口已废弃。
