### ISSUE TITLE
发布回答评论&&对回答评论的回复

### ISSUE THREAD

**Issue by Antipas** [ifLab/WeCenterMobile-Api#16]
这个居然要 GET、POST 同时请求，为什么不写到一起呢
![unknown](https://cloud.githubusercontent.com/assets/9331531/9979595/466f68a8-5fa7-11e5-95f2-20dd9a0c269b.jpeg)

**Comment by hihwei** [comment]
接口已更新，请查看最新文档：http://wecenter.api.hihwei.com/doku.php?id=question:save_answer_comment:%E8%AF%84%E8%AE%BA%E7%AD%94%E6%A1%88_%E5%9B%9E%E5%A4%8D%E7%AD%94%E6%A1%88%E8%AF%84%E8%AE%BA
