### ISSUE TITLE
需要下面一些API

### ISSUE THREAD

**Issue by billhu1996** [ifLab/WeCenterMobile-Api#24]
话题详情           api/topic.php
用户话题列别            api/my_focus_topic_ios.php
话题的精华回答           ?/api/topic/topic_best_answer/
更改用户信息            api/profile_setting.php
用户问题列表           api/my_question.php
用户回答列表           api/my_answer.php
用户文章列表           api/my_article.php
在上一版本WeCenter中,这些信息可以从后面的uri中获取到, 但是在这个版本中已经失效

**Comment by hihwei** [comment]
新增：http://wecenter.api.hihwei.com/doku.php?id=people:topics:%E5%85%B3%E6%B3%A8%E7%9A%84%E8%AF%9D%E9%A2%98%E5%88%97%E8%A1%A8

新增：http://wecenter.api.hihwei.com/doku.php?id=topic:topic:%E5%8D%95%E4%B8%AA%E8%AF%9D%E9%A2%98%E4%BF%A1%E6%81%AF

**Comment by hihwei** [comment]
新增：http://wecenter.api.hihwei.com/doku.php?id=topic:topic_best_answer_list:%E8%AF%9D%E9%A2%98%E7%9A%84%E7%B2%BE%E5%8D%8E%E5%9B%9E%E7%AD%94%E5%88%97%E8%A1%A8

新增：http://wecenter.api.hihwei.com/doku.php?id=people:user_actions:%E7%94%A8%E6%88%B7%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8_%E7%94%A8%E6%88%B7%E5%9B%9E%E7%AD%94%E5%88%97%E8%A1%A8_%E7%94%A8%E6%88%B7%E6%96%87%E7%AB%A0%E5%88%97%E8%A1%A8

**Comment by hihwei** [comment]
新增：http://wecenter.api.hihwei.com/doku.php?id=people:profile_setting:%E4%BF%AE%E6%94%B9%E4%B8%AA%E4%BA%BA%E4%BF%A1%E6%81%AF
