### ISSUE TITLE
文章详细信息中vote_info的值为空

### ISSUE THREAD

**Issue by billhu1996** [ifLab/WeCenterMobile-Api#26]
文章详细信息中vote_info的返回值为空
  "vote_info": {
        "id": 30,
        "uid": 3,
        "type": "article",
        "item_id": 30,
        "rating": 1,
        "time": 1439350026,
        "reputation_factor": 1,
        "item_uid": 19
      }

**Comment by hihwei** [comment]
如果vote_info为null，表示未表态
