### ISSUE TITLE
无法修改个人信息

### ISSUE THREAD

**Issue by billhu1996** [ifLab/WeCenterMobile-Api#28]
( api/people/profile_setting/ )修改个人信息 只能更改性别为保密(在男或女状态,使用postman,sex值设为1或2,性别都会被改为保密), 且其他信息无法修改并返回修改成功
{
  "rsm": "个人资料保存成功",
  "errno": 1,
  "err": null
}

**Comment by hihwei** [comment]
经测试，没问题。
