### ISSUE TITLE
回答的评论中@功能的歧义

### ISSUE THREAD

**Issue by billhu1996** [ifLab/WeCenterMobile-Api#29]
比如向后台发送字串："@lyn:@60:"，用户的本意是@lyn这个用户，并且对他说"@60:"，但是后台解析却误认为用户@了两遍lyn这个用户．

一个可行的解决方案是：@语法为简单的@id，对用户手动输入的@转义为@@的形式，手机端@用户的时候弹出用户选择列表保证
id存在，后台需检查id是否真实存在（因为有手动调用API的情况），若不真实存在，转义为@@的形式．

对于请求回答评论列表的API，返回的message字段采取数组的格式，每个元素为一个字典，样例如下：
    [
        {
            "type": "at",
            "user_id": 60
        },
        {
            "type": "string",
            "content": "@60"
        },
        {
            "type": "at"
            "user_id": 60
        },
        {
            "type": "string"
            "content": "@lyn@60"
        }
    ]
来表达"@lyn@@60@lyn@@lyn@@60"．

**Comment by hihwei** [comment]
建议手机端@用户的时候弹出用户列表（可调用用户搜索接口）供用户选择减少歧义。同时建议反馈给WeCenter官方处理。
