### ISSUE TITLE
用户相关Api文档中有错误

### ISSUE THREAD

**Issue by mzw1004** [ifLab/WeCenterMobile-Api#3]
其中的获取用户信息
URL：api/account/get_userinfo/ 
返回的应该只有是否关注了该用户

**Comment by hihwei** [comment]
这个接口返回的不是有 是否关注了该用户 还有我的话题数、我关注的人数等信息，具体请看：https://github.com/ifLab/WeCenterMobile-Api/blob/master/docs/API_Account.md#%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF
