### ISSUE TITLE
分享

### ISSUE THREAD

**Issue by Antipas** [ifLab/WeCenterMobile-Api#33]
分享一个回答、文章的时候，需要它的URL

**Comment by hihwei** [comment]
文章有单独的页面，回答没有。如果分享文章，建议直接拼接分享地址：域名host + ?  +  article  + 文章ID，如：http://wecenter.dev.hihwei.com/?/article/3；因回答没有单独页面，建议分享所属问题地址：域名host + ?  + question  + 问题ID，如：http://wecenter.dev.hihwei.com/?/question/7
