### ISSUE TITLE
请问启用app secret的时候如何登录？

### ISSUE THREAD

**Issue by yixtan** [ifLab/WeCenterMobile-Api#37]
后来启用了app secret，用post登录的时候返回验签失败。
curl -d "user_name=usrname&password=passwd&mobile_sign=3f99c90232f2b61e26d8be1e10fb98b0" "http://www.mysite.com/api/account/login_process/" -c request.cookie
这样对么？

**Comment by muyuren** [comment]
取请求的接口路径第二部分，如登录接口路径为：api/account/login_process/，第二部分即: account
取后台配置的某个AppSecret，如：12884789df747d7affbcd6a7cadd9359
将上述两个值进行拼接，拼接结果为：account12884789df747d7affbcd6a7cadd9359
对上述拼接结果进行md5加密操作得到签名，结果为：efeaf5de519976c71ec1204e331a1fd5
以GET方式带上签名访问相应的接口。参数名：mobile_sign，值：efeaf5de519976c71ec1204e331a1fd5，即：mobile_sign=efeaf5de519976c71ec1204e331a1fd5

**Comment by hihwei** [comment]
user_name 和 password 是POST方式，mobile_sign是GET方式。
