### ISSUE TITLE
用于展示用户信息 profile.php 在3.1环境下出错

### ISSUE THREAD

**Issue by HugeTimor** [ifLab/WeCenterMobile-Api#4]
返回结果带有其他数据，非纯净json无法正常解析，下面是返回结果：
<br />
<b>Strict Standards</b>:  Only variables should be assigned by reference in 
<b>/home/wwwroot/wecenter/api/core/Common.php</b> on line 
<b>277</b>
<br />
{"rsm":[{"uid":"2","user_name":"MB","sex":"0","birthday":null,"job_id":"0","signature":null}],"errno":1,"err":null}

**Comment by hihwei** [comment]
请直接访问  http://w.hihwei.com/api/profile.php?uid=1  测试，测过了，接口没问题的。
