### ISSUE TITLE
Strict Standards 统一提交

### ISSUE THREAD

**Issue by HugeTimor** [ifLab/WeCenterMobile-Api#7]
1.my_article.php（获取我的文章列表）
2. profile_setting.php（用于修改用户信息）
3. profile.php （用于展示用户信息）

my_question.php ，my_focus_question.php ，my_answer.php，my_focus_user.php，my_fans_user.php ,my_focus_topic.php

**Comment by hihwei** [comment]
测试发现都不存在问题，如有问题，请发问题详细截图。 上面列的部分接口已弃用，请查看 https://github.com/ifLab/WeCenterMobile-Api
